support: Innodb_redo_log_enabled
takutakahashi/database-restore-action pull request #3
Opened 2023-02-11 08:26 UTC by ryuichi1208

Thanks for the very useful tool! ! ! I came up with an idea that seems to be a little faster, so I'll propose it!

---

Add option to configure redo log disable released in MySQL 8.0.21. Enabling this option can speed things up by 20% to 30%.

ref: https://dev.mysql.com/doc/refman/8.0/en/innodb-redo-log.html#innodb-disable-redo-logging

#### benchmark

Here are the results of the benchmark in the local environment

```
# test file size
3.3G	test.dump

# redo log: Enable
real	14m3.015s

# redo log: Disable
real	11m17.501s

```

2023-02-12 13:03 UTC, takutakahashi requested changes

2023-02-12 13:03 UTC, takutakahashi commented on pkg/database/database.go
> +	if d.cfg.Database.DisableRedoLog {
I have a plan to support other database product, ex: postgresql.
It should not to apply this exec if database product can not support this ALTER.
Please add Type detection and checking supported version.

2023-02-12 13:04 UTC, takutakahashi commented
@ryuichi1208 Thanks for very good PR.
Please check comment and fix it.

2023-02-12 13:07 UTC, takutakahashi commented on pkg/database/database.go
> +	if d.cfg.Database.DisableRedoLog {
You need to add only `mysql` check. don't need to consider about other database. Because it's not appear for NOW!

2023-02-13 06:04 UTC, ryuichi1208 commented
Thanks for the review! Fixed:)

2023-02-20 05:33 UTC, takutakahashi approved these changes
LGTM!

2023-02-20 05:33 UTC, merged